sudo: required
services:
  - docker

before_install:
  - docker build -t anandp_pandav/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run anandp_pandav/react-test npm test -- --coverage

after_success:
  - docker build -t anandpandav/multi-client ./client
  - docker build -t anandpandav/multi-nginx ./nginx
  - docker build -t anandpandav/multi-server ./server
  - docker build -t anandpandav/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push anandpandav/multi-client
  - docker push anandpandav/multi-nginx
  - docker push anandpandav/multi-server
  - docker push anandpandav/multi-worker